name: Build and deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn -B package deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    - run: mkdir -p ./release/modules && cp -r ./gomint-server/target/modules/* ./release/modules/
    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: GoMint Server
        path: ./release/
    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
        username: gomint
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gomint/gomint
        tags: ${{ github.sha }}
    - uses: release-drafter/release-drafter@v5
      name: Create or update release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cd release/ && zip -r server.zip ./
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./release/server.zip
        AWS_REGION: 'eu-central-1'
        S3_BUCKET: gomint-artifacts
        S3_KEY: latest.zip
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
